export const environment = {
    production: false,
    tokenAPI: 'eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJmZmI3ZTk2YmUwZmUyZWMwMjM2MmQ3MTJlYTJlYzM1NiIsInN1YiI6IjY1M2ZmY2I0Y2M5NjgzMDBhZGU4MDFiOSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ._gVjgYZcqym80xAXZmlOjkPzUx7L5prVcXUPp6OxvMU'
};